server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://192.168.10.30:3306/shop?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: workflow
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
